version: '3.4'

services:
  nginx:
    image: nginx:${DJANGO_APP_NAME}
    build:
      context: ./nginx-data
      args:
        APP_NAME: ${DJANGO_APP_NAME}
        APP_PORT: ${DJANGO_PORT}
        LISTEN_PORT: ${NGINX_OUTSIDE_PORT}
    command: tail -f /dev/null 2>&1
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - ${NGINX_OUTSIDE_PORT}:${NGINX_PORT}
      # IF you use "https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion please comment out and use below ports settings"
      # - ${NGINX_PORT}
    volumes:
      - ./django_data/src/static:/static
      - ./django_data/src/media:/media
    depends_on:
      - nginx-unit
    restart: always

  # mariadb:
  #   image: 'mariadb:10.0.33'
  #   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=no
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #     - TZ=${MYSQL_TIMEZONE}
  #   volumes:
  #     - './mariadb_data:/var/lib/mysql'
  #   restart: always

  nginx-unit:
    build:
      context: ./nginx-unit-data
      args:
        APP_NAME: ${DJANGO_APP_NAME}
        APP_PORT: ${DJANGO_APP_PORT}
    stdin_open: true
    tty: true
    # command: bash -c '/init-scripts/init.sh ${DJANGO_APP_NAME} ${DJANGO_PORT}'
    ports:
      #     for develop
      # - ${DJANGO_OUTSIDE_PORT}:${DJANGO_PORT}
      #     for production
      - ${DJANGO_PORT}

    # depends_on:
    #   - mariadb
    volumes:
      - ./nginx-unit-data/src:/code
      # - ./nginx-unit-data/init-scripts:/docker-entrypoint-init.d
      - ./nginx-unit-data/state:/var/lib/unit
      - ./nginx-unit-data/init-scripts:/init-scripts
      - ./nginx-unit-data/log/unit.log:/var/log/unit.log
      - ./nginx-unit-data/config:/docker-entrypoint.d/
    restart: always

# volumes:
#   mariadb_data:
#     driver: local

networks:
  default:
    external:
      name: webproxy
